// React Student Dashboard/src/components/Student/StudentContent/BarChart/BarChart.jsx
import React from 'react';
import { useSelector } from 'react-redux';
import { Bar } from 'react-chartjs-2';
import { createBarChartData } from './bar-chart-utils';

const BarChart = ({ studentData }) => {
    
    // studentData could also be obtained from state by using index (must be passed as prop from StudentContent) 
    // averages all assignments from all students from state
    const averages = useSelector(state => state.average.assignments);

    // studentData (props) and averages (state) into function to keep component clean
    // function arguments: studentData(array), averages(array), indexAxis(string), maintainAspectRatio(boolean)
    const barChartData = createBarChartData(studentData, averages, 'x', true);

    // function returned object with properties data and option:
    const data = barChartData.data;
    const options = barChartData.options;
   
    return (
        <div className='student-content-bar-chart'>
            <Bar 
                options={options}
                data={data}
            />
        </div>
    );
};
 
export default BarChart;

// StudentDashboard/src/routes/BarChart.svelte
<script>
  import { Bar } from 'svelte-chartjs';
  // import Chart from 'chart.js/auto';
  import { createBarChartData } from './utils/bar-chart-utils.js';
  export let studentData;
  import { averageAllAssignments as averages } from './utils/assignments-utils.js';
  // Chart.register();

  const barChartData = createBarChartData(studentData, averages, 'x', true);
  const data = barChartData.data;
  const options = barChartData.options;
</script>

<div>
  <Bar {data} {options} />
</div>
