// React Student Dashboard/src/components/NavMenu/Navigation.jsx
import React from 'react';
import { useSelector } from 'react-redux';
import NavMenu from './NavMenu';
import NavMenuSmall from './NavMenuSmall';

const Navigation = () => {

    const windowWidth = useSelector(state => state.window.width);

    return ( 
        <nav >
            <div className='NavMenu'>
              {windowWidth > 600 ? <NavMenu /> : <NavMenuSmall />}
            </div>
        </nav>
    );
};
 
export default Navigation;

// FirstSvelteApp/src/Navigation.svelte
<script>
  import { wincData } from './json-to-js/data-utils.js';
  console.log(wincData);
  import NavMenu from './NavMenu.svelte';
</script>

<nav>
  <div>
    <!-- {windowWidth > 600 ? <NavMenu /> : <NavMenuSmall />} -->
    <NavMenu />
  </div>
</nav>

<!-- <nav >
    <div className='NavMenu'>
      {windowWidth > 600 ? <NavMenu /> : <NavMenuSmall />}
    </div>
</nav> -->
